// <auto-generated />
using CoreApp.DbAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CoreApp.DbAccess.Migrations
{
    [DbContext(typeof(ProdDbContext))]
    [Migration("20171226124803_Name")]
    partial class Name
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoreApp.DbAccess.Models.Category", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.HasKey("Code");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CoreApp.DbAccess.Models.Product", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DeliveryDate");

                    b.Property<string>("Description");

                    b.Property<bool>("IsAvailable");

                    b.Property<double>("Price");

                    b.HasKey("Code");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("CoreApp.DbAccess.Models.ProductCategory", b =>
                {
                    b.Property<int>("CategoryCode");

                    b.Property<int>("ProductCode");

                    b.HasKey("CategoryCode", "ProductCode");

                    b.HasIndex("ProductCode");

                    b.ToTable("ProductCategory");
                });

            modelBuilder.Entity("CoreApp.DbAccess.Models.ProductType", b =>
                {
                    b.Property<int>("Code");

                    b.Property<string>("Description");

                    b.HasKey("Code");

                    b.ToTable("ProductTypes");
                });

            modelBuilder.Entity("CoreApp.DbAccess.Models.Unit", b =>
                {
                    b.Property<int>("Code");

                    b.Property<string>("Description");

                    b.HasKey("Code");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("CoreApp.DbAccess.Models.ProductCategory", b =>
                {
                    b.HasOne("CoreApp.DbAccess.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoreApp.DbAccess.Models.Product", "Product")
                        .WithMany("Categories")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoreApp.DbAccess.Models.ProductType", b =>
                {
                    b.HasOne("CoreApp.DbAccess.Models.Product")
                        .WithOne("ProductType")
                        .HasForeignKey("CoreApp.DbAccess.Models.ProductType", "Code")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoreApp.DbAccess.Models.Unit", b =>
                {
                    b.HasOne("CoreApp.DbAccess.Models.Product")
                        .WithOne("Unit")
                        .HasForeignKey("CoreApp.DbAccess.Models.Unit", "Code")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
